### ISSUE TITLE
[Object] 플레이어 리소스 제작

### ISSUE THREAD

**Issue by Hamsik2rang** [Hamsik2rang/WeCandyFenceIt2#4]
* 오브젝트 세부 기획을 확인한 후 플레이어 리소스(폭격기)를 제작한다.

**Comment by Dadang2020** [comment]
![플레이어 리소스(폭격기)_1](https://user-images.githubusercontent.com/71388391/94311869-eb000800-ffb6-11ea-88dd-b87ffc8a96e2.png)

**Comment by Hamsik2rang** [comment]
issue close합니다. 수고했어요!
